version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health_ai_app_prod
    ports:
      - "8000:8000" 
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: ankane/pgvector:latest 
    container_name: health_ai_postgres_prod
    env_file:
      - .env.prod 
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data 
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER_PROD} -d ${POSTGRES_DB_PROD}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_prod:
    name: health_ai_postgres_data_prod
